### PR TITLE
Finalized core features of the development environment

### PR DESCRIPTION
**Pull request by Ex6tenze**
The following features have been added, tested, and documented on Windows, WSL, and Linux (Ubuntu, Arch)

- Laravel Sail scaffolding (Apache, PHP, MySQL, Mailpit)
- Jetstream scaffolding
- PostCSS pre-processor for CSS minimizing and structure
- Live reload / Hot Module Reload (vite dev server)
- Wiki documentation (Proper WSL installation) & Modified Readme
- Modified Laravel template workflow to accommodate automated PHPUnit testing

### CODE REVIEW

**Comment by Ex6tenze** [comment]
The merge conflict is from an earlier resolved security fix, and remains fixed in the incoming branch. As result, it can be overridden.

**Review by TimKardol — COMMENTED** [review]
I need to check if it works on my machine. But all the files just seem to be added because of importing new packages.

**Comment by Ex6tenze** [comment]
> I need to check if it works on my machine. But all the files just seem to be added because of importing new packages.

Correct, although a large part of this has also been making sure it works consistently and that there is appropriate documentation. The earliest versions tended to break across multiple operating systems or devices, which has now been corrected.

The Vite config did not work out of the box due to a WSL limitation (Which most, if not all developers will be using), the Laravel workflow lacked Node packages which were required for PHPUnit testing, and PostCSS will be used instead of SCSS due to compatibility with Tailwind, which is natively supported.

Following the instructions, I am now able to consistently make the project work on two different installations of Windows natively and within WSL, as well as native Arch Linux. As result, most of the work didn't necessarily go into installing the packages, but making sure they 'just work' and form a solid foundation for the following work to come.

**Comment by TimKardol** [comment]
Okay, so I have been testing but it seems that in the wiki when you install all the packages it doesn't mention anything about installing mysql. When I run the php artisan migrate:fresh command it complains that there is no driver.

**Comment by TimKardol** [comment]
Fix: sudo apt install php-mysql should be added to the wiki

**Comment by Ex6tenze** [comment]
> Fix: sudo apt install php-mysql should be added to the wiki. This fixes the driver issue. Although another issue arises after.

I recommend fully removing all built images and re-cloning env, then running sail up again. Docker already provides a Bridge driver between Sail and MySQL.

**Comment by TimKardol** [comment]
Yup, seems like the container was being built using the original volumes. Ignore the previous comments.

**Pull request merged**
