### PR TITLE
Revert "Revert "Feature - QR codes/ticket system""

### PR DESCRIPTION
**Pull request by TimKardol**
Reverts HZ-HBO-ICT/it-conference#568

### CODE REVIEW

**Comment by v-stamenova** [comment]
image
Acceptance env. threw this when testing there - not sure if it's applicable for production env.

**Comment by v-stamenova** [comment]
> image Acceptance env. threw this when testing there - not sure if it's applicable for production env.

If this issue occurs when Elio is hosting what needs to be done is to add to php config file (or create additional one) `extension=imagick`; might also need to add then ` "ext-imagick": "*"` to the `composer.json` but I am not sure. If you change the `composer.json` don't forget to update the `composer.lock` :)

**Review by v-stamenova — APPROVED** [review]

**Comment by TimKardol** [comment]
> > image Acceptance env. threw this when testing there - not sure if it's applicable for production env.
> 
> If this issue occurs when Elio is hosting what needs to be done is to add to php config file (or create additional one) `extension=imagick`; might also need to add then ` "ext-imagick": "*"` to the `composer.json` but I am not sure. If you change the `composer.json` don't forget to update the `composer.lock` :)

When you add something to the composer file and then run `composer install` should it not automatically add it to the lock file? Or is it just to make sure that it actually populates it?

**Comment by v-stamenova** [comment]
> > > image Acceptance env. threw this when testing there - not sure if it's applicable for production env.
> > 
> > 
> > If this issue occurs when Elio is hosting what needs to be done is to add to php config file (or create additional one) `extension=imagick`; might also need to add then ` "ext-imagick": "*"` to the `composer.json` but I am not sure. If you change the `composer.json` don't forget to update the `composer.lock` :)
> 
> When you add something to the composer file and then run `composer install` should it not automatically add it to the lock file? Or is it just to make sure that it actually populates it?

I am not sure to be honest, but I believe it is depending on the way you add in to the composer file - if you manually add it to the `composer.json` then the lock file will become outdated and conflict will occur. But if you `require` the package, then it should automatically handle it.

**Comment by TimKardol** [comment]
I will merge as soon as the merge conflicts are gone

**Comment by IGORnvk** [comment]
> I will merge as soon as the merge conflicts are gone

Fixed the conflicts, though did not test since I am at work, but it should be working as expected.

**Pull request merged**
