### PR TITLE
Feature/notifications and emails

### PR DESCRIPTION
**Pull request by v-stamenova**
The branch introduces a major refactor in the way approval/disapproval by the content moderator is handled. Instead of everything executed in the controller, the controller now dispatches events, listeners than handle and send out notifications as well. Previously it was only mails, now the notifications are stored in the database as well. All notifications are shown on my hub announcements currently. Also the branch introduces the possibility of turning off email notifications in the jetstream default profile page.

Quick note: as notifications I refer to the ones saved in the db, the mails are also notifications but I just refer to them as mails

For testing:
- [x] Need to migrate first - to get notifications table and the additional field for receiving emails in the users table
- [x] Approval\Disapproval of teams, presentations, booths and sponsorships works
- [x] When a team, presentation or sponsorship is approved, all participants receive generic email stating they have new notifications in the conference website (that new ... is joining the conference) - the main speaker (presentation) or the company rep (team and sponsorship) receive approval email. When they open the announcements page there are notifications as well
- [x] When a team, presentation, sponsorship, booth is disapproved or booth is approved only the company rep or main speaker receive emails & notifications about the status update
- [x] When the option about sending emails is disabled from the profile, no matter the role, the user will not receive email about approval/disapproval of something but will continue to receive the notifications
- [x] Only unread notifications are shown on the announcements page
- [x] For a notification to count as read, the user needs to mark it as read
- [x] Daily deletion of read notifications - done in the kernel, can see how many elements will be pruned with `sail artisan model:prune --pretend`

### CODE REVIEW

**Review by TimKardol — CHANGES_REQUESTED** [review]
In general this is approved. Most of the points are in the UI/UX part, which ofcourse is due for a rework. Backend looks good.

**Comment by v-stamenova** [comment]
Strongly suggest testing once more the teams and presentations once more before approval because of the conflict solving

**Comment by TimKardol** [comment]
@v-stamenova Are we waiting on approval from @dwaard ? What's the current status of this pr?

**Comment by v-stamenova** [comment]
> @v-stamenova Are we waiting on approval from @dwaard ? What's the current status of this pr?

We are refactoring this one with @dwaard on Monday afternoon

**Review by dwaard — APPROVED** [review]
Reviewed together with @v-stamenova because we both both added commits

**Pull request merged**
