### PR TITLE
Fix - Size of logos on companies page

### PR DESCRIPTION
**Pull request by IGORnvk**
Fixed the size of companies logos on the companies page so now it looks nice!

### CODE REVIEW

**Comment by IGORnvk** [comment]
Should I still add the borders around images? @TimKardol

**Comment by TimKardol** [comment]
Add the borders, I'll check how it looks.

**Comment by IGORnvk** [comment]
> Add the borders, I'll check how it looks.

Yeah well I did it, but it looks much worse imo..

**Comment by TimKardol** [comment]
Agreed, get rid of the borders and rounded edges. I think this fixes the issues we have been having. Can you also check the other issue about the sizes of the png/jpgs/etc? I think that is also a factor to consider.

**Review by TimKardol — CHANGES_REQUESTED** [review]
Remove the borders around the logo and then its approved!

**Review by TimKardol — APPROVED** [review]

**Pull request merged**
