### PR TITLE
Rework - gold sponsor flow

### PR DESCRIPTION
**Pull request by v-stamenova**
! The parent branch is rework/company-and-speakers. Also because I needed the fix of some issues I had to merge with #107 

The gold sponsor can finally have two presentations.
For testing:
After company has been approved as golden sponsor:
- [x]  The company rep can invite people as speakers
- [x] When the speaker accepts the invitation if the company doesn't have a presentation already, the speaker will be prompted to create it
- [x] When the speaker accepts the invitation if the company has a single presentation already, the speaker will be prompted to choose if they want to create another presentation or join the already existing one as a cospeaker
- [x] When the speaker accepts the invitation if the company has two presentations already, the speaker will be prompted to choose which one they would like to cohost

This update should not be messing the normal flow of companies and their speakers or the independent speakers!

### CODE REVIEW

**Comment by TimKardol** [comment]
In 'sidebar-link.blade.php' there is a weird thing going on.


I tried several things, but an extra pair of wouldn't hurt.

**Comment by v-stamenova** [comment]
Currently fixing an issue in #107 that may affect this PR. Don't merge even if approved :)

**Review by dwaard — APPROVED** [review]
Approved with a technical debt. I created #157 for this

**Comment by v-stamenova** [comment]
> In `sidebar-link.blade.php` there is a weird thing going on. `<!-- TODO/FIX: In dark mode the active link color does not work -->`
> 
> I tried several things, but an extra pair of eyes wouldn't hurt.

Done

**Comment by v-stamenova** [comment]
Notifications are added, but need redesign - #171

**Review by dwaard — APPROVED** [review]

**Pull request merged**
