### PR TITLE
Feature - Multiple editions

### LINKED ISSUE #410: Feature: Edition management
There should be a way for the content mod to prepare for the next edition of the conference while the old one is still ongoing, and, for example, start setting deadlines for future edition.

### PR DESCRIPTION
**Pull request by IGORnvk**
# Description

Pull request introduces an edition management feature as well as the deadlines for the edition.

ERD for this particular part of the application:
image

`editions` - previously called 'event_instance', represents edition (e.g. We are in IT together Conference 2024)
`events` - basically representing all the events that occur during the conference (e.g. Company registration, Presentation request etc.)
`edition_events` - table that connects events and edition during which these events are happening, and therefore it contains start and end dates for these events, since for every edition they can be different.

Note 1: the icons for editions/events should be changed, since I just copied them from another part of the application.

Note 2: 99% that I forgot to add something somewhere, so feel free to correct me.

closes #410 and #325

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## What needs to be tested

- [ ] CRUD Edition
- [ ] Edit (set dates) for Events
- [ ] Activate the Edition
- [ ] Switch between editions (make another edition active)
- [ ] Make sure the register buttons and button to request presentation appear when the start date of their event arrives and disappear when the end date arrives

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IGORnvk** [comment]
Still have to write some unit tests, but for now it can be opened for some manual testing and general review!

**Review by v-stamenova — CHANGES_REQUESTED** [review]
I am totally unable to test it, the moment I try to migrate fresh I get: 
image

**Review by v-stamenova — CHANGES_REQUESTED** [review]
All tests are failing - I'm especially more concerned about the build one.
I tried running it locally and again failing with similar error.

image

With around 83 commits and multiple failing tests, rather than trying to fix everything in this PR, it might be better to create a new PR/branch to address these issues. What do you think, @TimKardol?

**Comment by IGORnvk** [comment]
> All tests are failing - I'm especially more concerned about the build one. I tried running it locally and again failing with similar error.
> 
> image
> 
> With around 83 commits and multiple failing tests, rather than trying to fix everything in this PR, it might be better to create a new PR/branch to address these issues. What do you think, @TimKardol?

Yeah it is happening because of the Scheduler in console.php. It tries to retrieve current Edition when there is none, but I thought I fixed it already...

**Comment by TimKardol** [comment]
> > All tests are failing - I'm especially more concerned about the build one. I tried running it locally and again failing with similar error.
> > image
> > With around 83 commits and multiple failing tests, rather than trying to fix everything in this PR, it might be better to create a new PR/branch to address these issues. What do you think, @TimKardol?
> 
> Yeah it is happening because of the Scheduler in console.php. It tries to retrieve current Edition when there is none, but I thought I fixed it already...

I remember you fixing it haha

**Pull request closed without merging**
